language: php
dist: trusty


php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - COMPOSER_ROOT_VERSION=5.0.x-dev
    - DB=MYSQL
    - PDO=1
    - SS_ENVIRONMENT_TYPE="dev"
  matrix:
    - RECIPE_VERSION=4.3.x-dev
    - RECIPE_VERSION=4.4.x-dev
    - RECIPE_VERSION=4.5.x-dev



before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  -
  - composer require --no-update silverstripe/recipe-cms:$RECIPE_VERSION
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpcs -n -l src/ tests/php/
  - vendor/bin/phpunit -c "phpunit.xml" tests/php
  - vendor/bin/phpstan analyse src/ tests/ -c "phpstan.neon" -a vendor/symbiote/silverstripe-phpstan/bootstrap.php --level 4
