language: php
dist: xenial

services:
  - mysql

env:
  global:
    - COMPOSER_ROOT_VERSION=5.0.x-dev
    - DB=MYSQL
    - PDO=1
    - SS_ENVIRONMENT_TYPE="dev"
    - SS_BASE_URL="http://localhost:8080/"
matrix:
  fast-finish: true
  include:
    - php: 7.1
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL PDO=1 PHPUNIT_COVERAGE_TEST=1
    - php: 7.4
      env: DB=MYSQL PHPUNIT_TEST=1



before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  -
  - composer require --no-update silverstripe/recipe-cms:$RECIPE_VERSION
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpcs -n -l src/ tests/php/
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit -c "phpunit.xml" tests/php; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml tests/php; fi
  - vendor/bin/phpstan analyse src/ tests/ -c "phpstan.neon" -a vendor/symbiote/silverstripe-phpstan/bootstrap.php --level 4
after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
