---
Name: siteconfig-seo
Before:
  - 'tractorcow/silverstripe-fluent'
  - syntro/silvershare
---
---
Name: textdropdownfield
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'syntro/silverstripe-seo:client/dist/seo-field/main.js'


SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Syntro\SEO\Extensions\SiteConfigExtension
